resolver: lts-18.6
compiler: ghc-8.10.4

packages:
- .

ghc-options:
  "$locals": -funfolding-use-threshold=16 -fexcess-precision -optc-O3 -optc-ffast-math -O2 # -v

apply-ghc-options: locals

extra-deps:
  - git: https://github.com/hasktorch/hasktorch.git
    commit: 5f97cd3fa1647092de85e4675aebdc3da1967098
    subdirs:
      - hasktorch
      - libtorch-ffi
      - libtorch-ffi-helper
  - asciichart-1.0.2@sha256:59b62adb30078dbf96677c17167d156b093c8a2eb93068e0d3a3bd24b5d14b30,1561

extra-include-dirs:
  - libtorch/include/torch/csrc/api/include
  - libtorch/include

extra-lib-dirs:
  - ./libtorch/lib
